
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C200, LENGTH = 0x3E00
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
out2_4_0_buff_0 = .;
. += 0x200;
. = 0x44000;
out2_4_0_buff_1 = .;
. += 0x200;
. = 0x48000;
out1_4_0_cons_buff_0 = .;
. += 0x200;
. = 0x4C000;
out1_4_0_cons_buff_1 = .;
. += 0x200;
. = 0x40600;
in2_weights_0_4_cons_buff_0 = .;
. += 0x200;
. = 0x44200;
in2_weights_0_4_cons_buff_1 = .;
. += 0x200;
. = 0x50400;
out2_1_0_buff_0 = .;
. += 0x200;
. = 0x54000;
out2_1_0_buff_1 = .;
. += 0x200;
. = 0x58000;
out1_1_0_cons_buff_0 = .;
. += 0x200;
. = 0x5C000;
out1_1_0_cons_buff_1 = .;
. += 0x200;
. = 0x50600;
in2_weights_0_1_cons_buff_0 = .;
. += 0x200;
. = 0x54200;
in2_weights_0_1_cons_buff_1 = .;
. += 0x200;
. = 0x60400;
out2_6_0_buff_0 = .;
. += 0x200;
. = 0x64000;
out2_6_0_buff_1 = .;
. += 0x200;
. = 0x68000;
out1_6_0_cons_buff_0 = .;
. += 0x200;
. = 0x6C000;
out1_6_0_cons_buff_1 = .;
. += 0x200;
. = 0x60600;
in2_weights_0_6_cons_buff_0 = .;
. += 0x200;
. = 0x64200;
in2_weights_0_6_cons_buff_1 = .;
. += 0x200;
. = 0x70400;
out2_5_0_buff_0 = .;
. += 0x200;
. = 0x74000;
out2_5_0_buff_1 = .;
. += 0x200;
. = 0x78000;
out1_5_0_cons_buff_0 = .;
. += 0x200;
. = 0x7C000;
out1_5_0_cons_buff_1 = .;
. += 0x200;
. = 0x70600;
in2_weights_0_5_cons_buff_0 = .;
. += 0x200;
. = 0x74200;
in2_weights_0_5_cons_buff_1 = .;
. += 0x200;
  .bss : { *(.bss*) } > data
}
INPUT(smoke_fused_fused.mlir.prj\op0_mul.o)
PROVIDE(main = core_3_3);
