
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C004, LENGTH = 0x3FFC
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
inpff_fifo_buff_0 = .;
. += 0x1000;
. = 0x44000;
inpff_fifo_buff_1 = .;
. += 0x1000;
. = 0x48000;
ffi_L3L2_buff_0 = .;
. += 0x1000;
. = 0x4C000;
anm_in_cons_buff_0 = .;
. += 0x1000;
. = 0x41400;
anm_in_cons_buff_1 = .;
. += 0x1000;
. = 0x45000;
anm_in_cons_buff_2 = .;
. += 0x1000;
. = 0x4D000;
o_out_joined_0_cons_buff_0 = .;
. += 0x10;
. = 0x42400;
o_out_joined_0_cons_buff_1 = .;
. += 0x10;
. = 0x49000;
anm_oout_buf = .;
. += 0x1000;
. = 0x46000;
_anonymous16 = .;
. += 0x10;
. = 0x50400;
bo_mem_3_cons_buff_0 = .;
. += 0x1000;
. = 0x51400;
Co_3_buff_0 = .;
. += 0x4;
. = 0x54900;
Co_3_buff_1 = .;
. += 0x4;
. = 0x54000;
Ao_3_cons_buff_0 = .;
. += 0x900;
. = 0x58000;
Ao_3_cons_buff_1 = .;
. += 0x900;
. = 0x5C000;
_anonymous7 = .;
. += 0xC;
. = 0x7C000;
outL_fifo_buff_0 = .;
. += 0x4;
. = 0x70410;
outL_fifo_buff_1 = .;
. += 0x4;
. = 0x70400;
ffn_out_joined_0_cons_buff_0 = .;
. += 0x10;
. = 0x74000;
ffn_out_joined_0_cons_buff_1 = .;
. += 0x10;
. = 0x78000;
_anonymous17 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(layer_fused_skeleton_e2048_h8192_c8_g32_fused.mlir.prj\op0_layer_fused_2048_8192_g32.o)
PROVIDE(main = core_4_3);
