
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C010, LENGTH = 0x3FF0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
anm_inpff_buff_0 = .;
. += 0x1000;
. = 0x44000;
anm_in_cons_buff_0 = .;
. += 0x1000;
. = 0x48000;
anm_in_cons_buff_1 = .;
. += 0x1000;
. = 0x4C000;
anm_in_cons_buff_2 = .;
. += 0x1000;
. = 0x41400;
anm_ffi_l1l2_buff_0 = .;
. += 0x1000;
. = 0x49000;
o_out_joined_0_cons_buff_0 = .;
. += 0x10;
. = 0x4D000;
o_out_joined_0_cons_buff_1 = .;
. += 0x10;
. = 0x45000;
anm_oout_buf = .;
. += 0x1000;
. = 0x42400;
_anonymous4 = .;
. += 0x10;
. = 0x50400;
kqv_mem_1_cons_buff_0 = .;
. += 0x1000;
. = 0x51400;
Co_1_buff_0 = .;
. += 0x4;
. = 0x54900;
Co_1_buff_1 = .;
. += 0x4;
. = 0x54000;
Ao_1_cons_buff_0 = .;
. += 0x900;
. = 0x58000;
Ao_1_cons_buff_1 = .;
. += 0x900;
. = 0x5C000;
_anonymous1 = .;
. += 0xC;
. = 0x64000;
ffi_mem_1_cons_buff_0 = .;
. += 0x1000;
. = 0x68000;
Cgu_1_buff_0 = .;
. += 0x10;
. = 0x6C000;
Cgu_1_buff_1 = .;
. += 0x10;
. = 0x60400;
Agu_1_cons_buff_0 = .;
. += 0x2400;
. = 0x62800;
_anonymous6 = .;
. += 0xC;
. = 0x74000;
ffi_mem_0_cons_buff_0 = .;
. += 0x1000;
. = 0x78000;
Cgu_0_buff_0 = .;
. += 0x10;
. = 0x7C000;
Cgu_0_buff_1 = .;
. += 0x10;
. = 0x70400;
Agu_0_cons_buff_0 = .;
. += 0x2400;
. = 0x72800;
_anonymous5 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(post_attn_fused_legacy_e2048_h8192_c4_g32_fused.mlir.prj\op0_post_attn_fused_2048k_g32.o)
PROVIDE(main = core_1_3);
