
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C00C, LENGTH = 0x3FF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
kqv_mem_2_cons_buff_0 = .;
. += 0x1000;
. = 0x41400;
Co_2_buff_0 = .;
. += 0x4;
. = 0x44900;
Co_2_buff_1 = .;
. += 0x4;
. = 0x44000;
Ao_2_cons_buff_0 = .;
. += 0x900;
. = 0x48000;
Ao_2_cons_buff_1 = .;
. += 0x900;
. = 0x4C000;
_anonymous2 = .;
. += 0xC;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x70400;
kqv_mem_3_cons_buff_0 = .;
. += 0x1000;
. = 0x71400;
Co_3_buff_0 = .;
. += 0x4;
. = 0x74900;
Co_3_buff_1 = .;
. += 0x4;
. = 0x74000;
Ao_3_cons_buff_0 = .;
. += 0x900;
. = 0x78000;
Ao_3_cons_buff_1 = .;
. += 0x900;
. = 0x7C000;
_anonymous3 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(post_attn_fused_legacy_e2048_h8192_c4_g32_fused.mlir.prj\op0_post_attn_fused_2048k_g32.o)
PROVIDE(main = core_0_5);
