
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C00C, LENGTH = 0x3FF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
bq_mem_3_cons_buff_0 = .;
. += 0x1000;
. = 0x41400;
Cqkv_4_buff_0 = .;
. += 0x4;
. = 0x44900;
Cqkv_4_buff_1 = .;
. += 0x4;
. = 0x44000;
Aqkv_4_cons_buff_0 = .;
. += 0x900;
. = 0x48000;
Aqkv_4_cons_buff_1 = .;
. += 0x900;
. = 0x4C000;
_anonymous4 = .;
. += 0xC;
. = 0x50400;
bo_mem_3_cons_buff_0 = .;
. += 0x1000;
. = 0x51400;
Co_3_buff_0 = .;
. += 0x4;
. = 0x54900;
Co_3_buff_1 = .;
. += 0x4;
. = 0x54000;
Ao_3_cons_buff_0 = .;
. += 0x900;
. = 0x58000;
Ao_3_cons_buff_1 = .;
. += 0x900;
. = 0x5C000;
_anonymous11 = .;
. += 0xC;
. = 0x6C000;
inter_4_buff_0 = .;
. += 0x800;
. = 0x61600;
inter_4_buff_1 = .;
. += 0x800;
. = 0x68000;
ffi_mem_3_cons_buff_0 = .;
. += 0x1000;
. = 0x60400;
Agu_4_cons_buff_0 = .;
. += 0x1200;
. = 0x64000;
Agu_4_cons_buff_1 = .;
. += 0x1200;
. = 0x65200;
_anonymous20 = .;
. += 0xC;
. = 0x70400;
bo_mem_4_cons_buff_0 = .;
. += 0x1000;
. = 0x71400;
Co_4_buff_0 = .;
. += 0x4;
. = 0x74900;
Co_4_buff_1 = .;
. += 0x4;
. = 0x74000;
Ao_4_cons_buff_0 = .;
. += 0x900;
. = 0x78000;
Ao_4_cons_buff_1 = .;
. += 0x900;
. = 0x7C000;
_anonymous12 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(layer_dense_e2048_h8192_c8_g32_fused.mlir.prj\op0_layer_fused_2048_8192_g32.o)
PROVIDE(main = core_4_3);
